language: groovy
jdk:
  - oraclejdk7
branches:
  only:
    - develop
    - master
    - travis_setup

before_script:
  - rm -rf target

script: ./grailsw refresh-dependencies
  && ./grailsw "test-app"

after_script: $TRAVIS_TEST_RESULT

notifications:
  email:
    - smlsun@gmail.com
    - ppelize@gmail.com